[package]
name = "color-eyre"
version = "0.5.8-alpha.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "An error report handler for panics and eyre::Reports for colorful, consistent, and well formatted error reports for all kinds of errors."
repository = "https://github.com/yaahc/color-eyre"
documentation = "https://docs.rs/color-eyre"
readme = "README.md"
categories = []
keywords = []

[features]
default = ["track-caller", "capture-spantrace"]
capture-spantrace = ["tracing-error", "color-spantrace"]
issue-url = ["url"]
track-caller = []

[dependencies]
eyre = "0.6.1"
tracing-error = { version = "0.1.2", optional = true }
backtrace = { version = "0.3.48", features = ["gimli-symbolize"] }
indenter = "0.3.0"
owo-colors = "1.0.3"
color-spantrace = { version = "0.1.4", optional = true }
once_cell = "1.4.0"
url = { version = "2.1.1", optional = true }

[dev-dependencies]
tracing-subscriber = "0.2.5"
tracing = "0.1.13"
pretty_assertions = "0.6.1"
thiserror = "1.0.19"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.15"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.dev.package.backtrace]
opt-level = 3

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "Unreleased"
replace="{{version}}"

[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
search = "#!\\[doc\\(html_root_url.*"
replace = "#![doc(html_root_url = \"https://docs.rs/{{crate_name}}/{{version}}\")]"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace="...{{tag_name}}"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "ReleaseDate"
replace="{{date}}"

[[package.metadata.release.pre-release-replacements]]
file="CHANGELOG.md"
search="<!-- next-header -->"
replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate"
exactly=1

[[package.metadata.release.pre-release-replacements]]
file="CHANGELOG.md"
search="<!-- next-url -->"
replace="<!-- next-url -->\n[Unreleased]: https://github.com/yaahc/{{crate_name}}/compare/{{tag_name}}...HEAD"
exactly=1
