[package]
name = "color-eyre"
version = "0.4.1"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "An error report handler for panics and eyre::Reports for colorful, consistent, and well formatted error reports for all kinds of errors."
repository = "https://github.com/yaahc/color-eyre"
documentation = "https://docs.rs/color-eyre"
readme = "README.md"
categories = []
keywords = []

[features]
default = ["capture-spantrace"]
capture-spantrace = ["tracing-error", "color-spantrace"]

[dependencies]
eyre = "0.5.0"
tracing-error = { version = "0.1.2", optional = true }
color-backtrace = "0.4.0"
backtrace = "0.3.48"
indenter = "0.3.0"
ansi_term = "0.11"
color-spantrace = { version = "0.1.3", optional = true }
once_cell = "1.4.0"

[dev-dependencies]
tracing-subscriber = "0.2.5"
tracing = "0.1.13"
pretty_assertions = "0.6.1"
thiserror = "1.0.19"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.dev.package.backtrace]
opt-level = 3
