[package]
name = "color-eyre"
version = "0.2.2"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A custom context for the `eyre` crate for colorful error reports, suggestions, and `tracing-error` support."
repository = "https://github.com/yaahc/color-eyre"
documentation = "https://docs.rs/color-eyre"
readme = "README.md"
categories = []
keywords = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
capture-spantrace = ["tracing-error", "color-spantrace"]

default = ["capture-spantrace"]

[dependencies]
eyre = "0.3.8"
tracing-error = { version = "0.1.2", optional = true }
color-backtrace = "0.4.0"
backtrace = "0.3"
indenter = "0.2.0"
ansi_term = "0.12.1"
color-spantrace = { version = "0.1.1", optional = true }


[dev-dependencies]
tracing-subscriber = "0.2.5"
tracing = "0.1.13"
